### ISSUE TITLE
Rationale clarification

### ISSUE THREAD

**Issue by GodsBoss** [Hochfrequenz/mako_time_converter#16]
The current ["Rationale" section in README](https://github.com/Hochfrequenz/mako_time_converter/blob/2a0251210c6fe71248d8668865996152de80e1a2/README.md#rationale) states:

> and you shall always use UTC-offset 0 (which makes things unnecessary complicated)

Currently it reads like I shall use UTC offset 0 to make things unnecessary complicated, I guess that's not the intention.

**Comment by hf-kklein** [comment]
@GodsBoss would this be clearer? https://github.com/Hochfrequenz/mako_time_converter/pull/17
